# Generated by Django 3.2.6 on 2022-04-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('smallName', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorCode', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.BigIntegerField(default=0)),
                ('currency', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexFrom', models.IntegerField()),
                ('indexTo', models.IntegerField()),
                ('heightFacadeFrom', models.IntegerField()),
                ('heightFacadeTo', models.IntegerField()),
                ('liftType', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.lifttype')),
                ('nameBrand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.namebrend')),
                ('vendorCode', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.vendorcode')),
            ],
        ),
    ]
