# Generated by Django 3.2.6 on 2022-04-12 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcode',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.currency'),
        ),
    ]
