# Generated by Django 3.2.6 on 2022-04-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0002_alter_vendorcode_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationtable',
            name='liftType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.lifttype'),
        ),
        migrations.AlterField(
            model_name='calculationtable',
            name='nameBrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.namebrend'),
        ),
        migrations.AlterField(
            model_name='calculationtable',
            name='vendorCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.vendorcode'),
        ),
    ]
