# Generated by Django 3.2.6 on 2022-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0003_auto_20220413_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifttype',
            name='tipon',
            field=models.BooleanField(default=False),
        ),
    ]
