# Generated by Django 3.2.6 on 2022-04-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0004_lifttype_tipon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationTableWeightFacade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightFacadeFrom', models.IntegerField()),
                ('weightFacadeTo', models.IntegerField()),
                ('heightFacadeFrom', models.IntegerField()),
                ('heightFacadeTo', models.IntegerField()),
                ('liftType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.lifttype')),
                ('nameBrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.namebrend')),
                ('vendorCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifts.vendorcode')),
            ],
        ),
    ]
