# Generated by Django 3.2.6 on 2021-09-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_children', to='nomenclatura.folder', verbose_name='Родиельская папка')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomenclatura.folder')),
            ],
        ),
    ]
